### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function

### ISSUE THREAD

**Issue by s41n1k** [smiegles/extract-relative-url-heapsnapshot#1]
how to fix this?
```
/mytool/extracturl# node main.js https://uber.com/
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/root/mytool/extracturl/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/mytool/extracturl/node_modules/puppeteer/lib/cjs/node/BrowserFetcher.js:48:39)

```

**Comment by smiegles** [comment]
He! Which Node version are you on? I'm on v14.5.0.

**Comment by s41n1k** [comment]
node version v8.10.0
