### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by mohammed-sec2010** [smiegles/extract-relative-url-heapsnapshot#2]
ali-VirtualBox extract-relative-url-heapsnapshot # node main.js https://tweetdeck.twitter.com/
/home/ali/Automated-Scanner/extract-relative-url-heapsnapshot/main.js:10
async function init(url) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
ali-VirtualBox extract-relative-url-heapsnapshot #

**Comment by smiegles** [comment]
He! Which Node version are you on? I'm on v14.5.0.
