### ISSUE TITLE
Error #2

### ISSUE THREAD

**Issue by CristiVlad25** [smiegles/extract-relative-url-heapsnapshot#3]
This is what I get

node main.js https://google.com/
(node:135776) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0714/164721.751903:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/tools/jsheapdump/node_modules/puppeteer/lib/cjs/node/BrowserRunner.js:193:20)
    at Interface.helper_1.helper.addEventListener (/root/tools/jsheapdump/node_modules/puppeteer/lib/cjs/node/BrowserRunner.js:183:65)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:135776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:135776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by smiegles** [comment]
He! Which Node version are you on? I'm on v14.5.0.

**Comment by CristiVlad25** [comment]
It has to do with the chrome extension as you can see. I'm on the latest
version of node available in Kali which is 10.20

**Comment by IshaanOhri** [comment]
It's because the OS is a 32Bit. So according to google, it cannot run a binary so it executes the supposed binary as a bash script. I'm not 100% sure but I feel this is the issue.
